import { Skill } from '../../types'

export const SKILLS: Skill[] = [
   { name: 'React', startYear: 2023 },
   { name: 'HTML5', startYear: 2021 },
   { name: 'CSS3', startYear: 2021 },
   { name: 'Three.js', startYear: 2022 },
   { name: 'Chart.js', startYear: 2023 },
   { name: 'Tailwind CSS', startYear: 2023 },
   { name: 'Bootstrap', startYear: 2022 },
   { name: 'Next.js', startYear: 2023 },
   { name: 'Radix UI', startYear: 2023 },
   { name: 'Shadcn UI', startYear: 2023 },
   { name: 'Framer Motion', startYear: 2024 },

   { name: 'Node.js', startYear: 2022 },
   { name: 'Express.js', startYear: 2022 },
   { name: 'SQL', startYear: 2022 },
   { name: 'MySQL', startYear: 2022 },
   { name: 'PostgreSQL', startYear: 2023 },
   { name: 'TimescaleDB', startYear: 2023 },
   { name: 'NoSQL', startYear: 2023 },
   { name: 'SQLite', startYear: 2022 },
   { name: 'MongoDB', startYear: 2023 },
   { name: 'Oracle SQL', startYear: 2024 },
   { name: 'Redis', startYear: 2025 },

   { name: 'JavaScript', startYear: 2021 },
   { name: 'TypeScript', startYear: 2023 },
   { name: 'Python', startYear: 2021 },
   { name: 'Java', startYear: 2020 },

   { name: 'JSON Web Tokens (JWT)', startYear: 2022 },
   { name: 'Role-based Access Control (RBAC)', startYear: 2022 },
   { name: 'Web Security (CORS/CSP/HSTS)', startYear: 2022 },
   { name: 'Snyk (Vulnerability Scanning)', startYear: 2022 },
   { name: 'Burp Suite', startYear: 2022 },
   { name: 'OAuth 2.0', startYear: 2022 },
   { name: 'Wireshark', startYear: 2022 },
   { name: 'nmap', startYear: 2022 },

   { name: 'Git', startYear: 2022 },
   { name: 'GitHub', startYear: 2022 },
   { name: 'Firebase', startYear: 2022 },
   { name: 'Cloudflare', startYear: 2025 },
   { name: 'GoDaddy', startYear: 2022 },
   { name: 'Vercel', startYear: 2024 },
   { name: 'Netlify', startYear: 2024 },
   { name: 'Render', startYear: 2023 },
   { name: 'Docker', startYear: 2024 },
   { name: 'AWS', startYear: 2023 },
   { name: 'Google Cloud', startYear: 2023 },

   { name: 'Generative AI', startYear: 2023 },
   { name: 'AI/ML Frameworks', startYear: 2025 },
   { name: 'Prompt Engineering', startYear: 2025 },
   { name: 'RAG (Retrieval Augmented Generation)', startYear: 2025 },

   { name: 'Adobe Photoshop', startYear: 2023 },
   { name: 'Canva', startYear: 2023 },
   { name: 'Figma', startYear: 2023 },
   { name: 'Linear', startYear: 2025 },
   { name: 'Robotic Process Automation (RPA)', startYear: 2023 },
   { name: 'Microsoft Power Automate', startYear: 2024 },
]
